config:
  target: "https://lambda.us-east-1.amazonaws.com"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Simple Load test
      
scenarios:
  - name: "Testing Redis with single command"
    flow:
      - post:
          url: "/2015-03-31/functions/arn:aws:lambda:us-east-1:681984993362:function:redis-stack-charge_request_redis-lambda-fn/invocations"
          json:
            unit: 1